select * from sales;
select customer_name, city from sales;
select * from sales where city = 'Delhi';
select * from sales where product_category = 'Clothing';
select * from sales where payment_method = 'UPI';
select count(*) from sales;
select sum(total_amount) from sales;
select avg(total_amount) from sales;
select min(price) from sales;
select mAX(price) from sales;
select city, count(*) from sales group by city;
select product_category, sum(total_amount) from sales group by product_category;
select payment_method, count(*) from sales group by payment_method;
select order_status, count(*) from sales group by order_status;
select city, avg(total_amount) from sales group by city;
select * from sales order by total_amount DESC;
select product_name, price from sales order by price DESC;
select customer_name, total_amount from sales order by total_amount desc;
select distinct city from sales order by city;
select city, sum(total_amount) from sales group by city order by sum(total_amount);
select * from sales where customer_name like "A%";
select * from sales where product_name like "%shoes%";
select * from sales where city like "%delhi%";
select * from sales where product_category like "%Electronics%";
select * from sales where product_name like "%watch%";
select * from sales limit 5;
select * from sales order by total_amount desc limit 3;
select * from sales order by price desc limit 5;
select city, Sum(total_amount) from sales group by city order by sum(total_amount) desc limit 5;
select * from sales order by order_date limit 5;
select * from sales limit 5 offset 5;
select * from sales order by total_amount desc limit 3 offset 2;
select product_name from sales limit 5 offset 3;
select customer_name from sales order by customer_name limit 5 offset 5;
select city from sales limit 5 offset 2;
select product_category, Sum(quantity) from sales group by product_category order by sum(quantity) desc;
select city, count(*) from sales where order_status = "delivered" group by city;
select sum(total_amount), payment_method from sales group by payment_method order by sum(total_amount) desc;
select sum(quantity), product_name from sales group by product_name order by sum(quantity) desc limit 5;
select city, avg(total_amount) from sales group by city order by avg(total_amount) desc;